# Generated by Django 4.2.1 on 2023-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employeeinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.IntegerField()),
                ("emp_name", models.CharField(max_length=100)),
                ("emp_address", models.CharField(max_length=200)),
                ("emp_email", models.EmailField(max_length=200)),
                ("emp_phone", models.CharField(max_length=20)),
            ],
        ),
    ]
